### ISSUE TITLE
Put legend in demo to the bottom

### ISSUE THREAD

**Issue by jcubic** [Roche/ggtips#11]
There may be a bug in ggtips when point is near right side of the plot, found in our application. If we put legend at bottom we will see in demo if problem is in ggtips.

**Comment by cosi1** [comment]
@jcubic The example app works good with legend in the bottom:

![Screen Shot 2019-08-09 at 16 06 34](https://user-images.githubusercontent.com/1132922/62784884-c0f03b80-babf-11e9-9921-b863e01fa8d2.jpg)
