### ISSUE TITLE
Unit tests don't pass with the newer versions of ggplot2

### ISSUE THREAD

**Issue by cosi1** [Roche/ggtips#13]
Version 3.0.0 of ggplot2 introduced some backwards incompatible changes to the low-level structure of ggplot objects. It appears that some of these changes break some of ggplot's unit tests.

### Steps to reproduce:
Build ggtips with ggplot2 >=3.0.0, and run unit tests.

**Comment by jcubic** [comment]
I would try to make it work with both version 2.x.x and 3.x.x and hope they will not make much internal changes in 3.x.x (My code was once broken by bugfix that introduced breaking change but not to public API).

**Comment by cosi1** [comment]
Issue addressed by #17
