### ISSUE TITLE
Tooltips not showing up in Basilisk Browser

### ISSUE THREAD

**Issue by cosi1** [Roche/ggtips#14]
### Observed effect:
The demo app, when viewed in Basilisk Browser for Linux, displays a static plot.
The following error is shown in the JS console upon every hovering over a point:

```
NS_ERROR_FAILURE:
  $.fn.ggtips/</<     http://127.0.0.1:3838/shared/jquery.min.js%20line%202%20%3E%20eval:81:31
  $.fn.proximity/</<  http://127.0.0.1:3838/shared/jquery.min.js%20line%202%20%3E%20eval:326:33
  dispatch            http://127.0.0.1:3838/shared/jquery.min.js:3:12392
  add/r.handle        http://127.0.0.1:3838/shared/jquery.min.js:3:9156
```

### Environment:
Basilisk Browser 2018.07.18 (64-bit)
User agent: Mozilla/5.0 (X11; Linux x86_64; rv:52.9) Gecko/20100101 Goanna/4.1 Firefox/52.9 Basilisk/20180718

EDIT: Updating Basilisk to the latest version (2019.06.08) doesn't help.

**Comment by jcubic** [comment]
I'm not sure if the browser will run on my system I have XFce that use GTK2, I have FireFox. If it will not run I will try to install something on VirtualBox.

**Comment by jcubic** [comment]
This may be related to jQuery version, did you check any other more complex shiny application in that browser?

**Comment by jcubic** [comment]
@cosi1 the demo at https://jcubic.shinyapps.io/ggtips/ works fine in Basilisk on GNU/Linux (Fedora 29).

**Comment by cosi1** [comment]
Example apps from RStudio seem to be working fine (jQuery 1.10.2). Dean Attali's samples too (jQuery 1.12.4).

ggtips runs with jQuery 1.12.4.

**Comment by cosi1** [comment]
> the demo at https://jcubic.shinyapps.io/ggtips/ works fine in Basilisk on GNU/Linux (Fedora 29).

I checked it and it works! Apparently it's an issue with the local instance of the app - will investigate.
