### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by jcubic** [Roche/ggtips#21]
https://travis-ci.org/Roche/ggtips/jobs/571269675

![travis](https://user-images.githubusercontent.com/280241/62939137-d8396c80-bdd0-11e9-8f42-a23d86f9f570.png)

**Comment by jcubic** [comment]
it seems that there Travis is invoked twice when creating PR first on push in branch that failed and on PR when it succeed. The same happen in this PR https://github.com/Roche/ggtips/pull/19

**Comment by jcubic** [comment]
To test, you need to create PR.

**Comment by cosi1** [comment]
Seems to persist: https://travis-ci.org/Roche/ggtips/jobs/601199820 -- this time it failed during Git checkout.

I don't think we are able to fix that, though.

**Comment by jcubic** [comment]
This was errored because I've used `push -f`, errored si when you kill the build with commit.

**Comment by jcubic** [comment]
The original issue was fail of tests in R.

**Comment by jcubic** [comment]
@cosi1 There are failing tests after your last commit to master, maybe some dependency change, there are two envs that runs in Travis one of them is failing.
