### ISSUE TITLE
Using ggtips with other geoms

### ISSUE THREAD

**Issue by Teett** [Roche/ggtips#23]
Hi there, I hope you guys are doing great,

First of all, thank you for developing this amazing package. I'm having issues adding reactive tooltips to a geom_bar. Here is the reproducible example that is an adaptation of your demo.

`    output$myPlot <- renderWithTooltips(
        plot = ggplot(iris, aes(x = Sepal.Width, y = Sepal.Length)) + 
geom_bar(stat = "identity",aes(fill = Species)),
        varDict = list(Sepal.Width = "Width", Sepal.Length = "Length", Species = "Species")
    )`

Please let me know if this is possible! Thank you again.

**Comment by jcubic** [comment]
It don't work with your example at the moment, but this is something we can try to add.

From front end perspective there would be one problem:

![ggplot](https://user-images.githubusercontent.com/280241/64378134-4ff36380-d02c-11e9-90b4-e61a25fb136c.png)

The single bar in one color is created with with multiple rect elements in SVG so if there would be a tooltip on single bar there would be need for showing it on center of each part of the single color bar (it will move while you move cursor vertically on single color) an. But maybe if generated data from backend have top edge of the bar it would be possible to show it only at one position of the bar. @cosi1 is something like this possible?

**Comment by cosi1** [comment]
Hello, @Teett, and thank you for the kind words!

Unfortunately, so far we have implemented tooltips only for point geometries – as you can see, this is an early version of the package and we're still actively developing it.

@jcubic It's possible! There are other related issues that we'll have to solve (e.g., plot orientation: not always will the top of the bar be on its top ;-) ), so it's a much more complex matter than tooltips for points.

**Comment by cosi1** [comment]
Hello @Teett ,

I don't know if you're still interested, but one user shared a workaround: you can use point geometry "under the hood", hidden behind the geometry of your liking (e.g., on top of a bar).

I know it's a dirty hack at best, but implementing that in a proper manner might take us a while...

**Comment by lmklima** [comment]
I agree that this is a great package, but I too got thrown off trying to make it work with a geom_boxplot. (It worked great once I changed to geom_point.) I do see that the package is still being updated and developed, which is nice to see. Thanks!

**Comment by jcubic** [comment]
@lmklima We are in process of adding box plot support. We investigate working with Box plot, now we are investigating pie charts (box plot with polar coords) and when we finish investigating pie charts we will implement both. But I'm not sure when it will happen.
