### ISSUE TITLE
Make first param of renderWithToolTips() an expr instead of plot object

### ISSUE THREAD

**Issue by olyerickson** [Roche/ggtips#24]
`renderWithToolTips()` is not currently "plug-compatible" (ie interchangeable) with functions like `renderPlot()`. This doesn't matter if the only contents of `renderPlot{(...)}` is a ggplot "stack," but it gets tricky if we are doing other things inside our `render*()` code...

Thanks!

**Comment by jcubic** [comment]
@cosi1  I thinking maybe something like this:

```R
renderUi({
   ggtipsPlot({ ... })
})
```

We don't need this wrapper, which I think is very poor API decision.

This is the code for the function, (take from what's inside `shiny::installExprFunction` in [R/main.R#L52](https://github.com/Roche/ggtips/blob/master/R/main.R#L52)).

```R
ggtipsPlot <- function(plot,
                               varDict,
                               plotScales = NULL,
                               callback = NULL,
                               point.size = 10,
                               dpi = 72,
                               width = NA,
                               height = NA,
                               customGrob = NULL,
                               ...) {
  if (!requireNamespace("shiny")) {
    stop("renderWithTooltips() requires Shiny")
  }
    res <- ggtips::getSvgAndTooltipdata(
      plot = plot, 
      varDict = varDict, 
      plotScales = plotScales, 
      callback = callback, 
      point.size = point.size, 
      dpi = dpi, 
      width = width, 
      height = height, 
      customGrob = customGrob,
      ...
    )
    ggtips::htmlWithGivenTooltips(
      svg = res$svg, 
      data = res$data, 
      height = height, 
      width = width, 
      point.size = point.size
    )
}
```

**Comment by cosi1** [comment]
Hmm... correct me if I'm wrong, but I believe that `renderWithTooltips()` is not unlike other `render*()` functions - you can put any valid block of expressions into `plot`, and it will be executed on every reactive trigger.

**Comment by jcubic** [comment]
How you should write code like this then?
```
foo <- calculate()
bar <- process(foo)
plot = bar # this go to plot render function.
```


normal render function have have single expression as params that should return whatEver it needs.

You will need to use gimmicks like this
```
renderWithToolTips(plot = {foo <- calculate(); bar <- process(foo); bar}, 
```
this don't look like valid clean R (I don't even sure if it will work)

**Comment by cosi1** [comment]
That's *exactly* how expression blocks in Shiny renderers work :-)

```
renderPlot({
  foo()
  bar()
})
```
is equivalent to
```
renderPlot(
  expr = { foo(); bar(); }
)
```

**Comment by jcubic** [comment]
I know but our lib don't you need to add named arguments default are two, so the code don't look the same. I shiny you have single expression.

**Comment by cosi1** [comment]
We can rename `plot` to `expr` then :-)

**Comment by jcubic** [comment]
But second is also required, it don't look like shiny code:

IMHO this is better:
```
renderUi({
   ggtipsPlot({ ... })
})
```
and it simplify the code because we don't need to register render function.

**Comment by cosi1** [comment]
To me it looks like adding complexity (two nested functions instead of one). And it would be a backwards-incompatible change in our API...

**Comment by jcubic** [comment]
It's orthogonal with shiny, version before 1.0 can change the API, and we don't need to change it both API can be side by side, right now this new API can be implemented in user code so this will be like shortcut.

with shiny and ggplot you usually have ggplot call in renderPlot
```R
renderPlot({
   ggplot(...)
})
```
with our API we will have:
```R
renderPlot({

   ggtipsPlot(ggplot(...), varDics = )
})
```

we are adding one more function not two. (and we need to use renderUI instead of renderPlot of course).

**Comment by cosi1** [comment]
I still fail to see the superiority of this approach...
If you file a PR, I'll approve it, but I'm not totally convinced ;-)

**Comment by jcubic** [comment]
The shorter name is always better, the function should do one thing and it should be named with one noun if possible. This is unwritten rule of any API and any good code. That's way keywords in any language is always one word. `renderWithToolTips` i 4 words combo which don't look very good. Perfect would be `ggtips::plot()`

**Comment by jcubic** [comment]
New api add with version 0.3.0 check readme for details.
