### ISSUE TITLE
Some tooltips are not displayed in firefox

### ISSUE THREAD

**Issue by mjakubczak** [Roche/ggtips#36]
Reproduction:
open demo app in firefox: https://jcubic.shinyapps.io/ggtips/

expected: all tooltips are displayed properly
observed: some tooltips don't show up + there's an error in the console 
![Screenshot from 2020-05-08 12-37-35](https://user-images.githubusercontent.com/29655451/81398168-fbf3ce00-9128-11ea-8962-3ba292632d2e.png)

**Comment by jcubic** [comment]
I wanted to report the bug to Firefox, I have no idea but it's works (don't throw exception)

```javascript
[...document.querySelectorAll('rect')].filter(x => x.clientWidth === 0)[0].getBBox()
```
The issue in ggtips is fixed but I have no idea why it don't throw exception now.
